import {useEffect,useRef,useState,type FormEvent} from 'react'
import {CURRENT_BUSINESSES,PUBLIC_HOURS,PUBLIC_PAINS} from '../domain/public'
import {GUIDANCE} from '../domain/guidance'
import {SubmissionForm} from './SubmissionForm'
import {useSubmission} from './useSubmission'
type Stage='questions'|'ideas'|'contact'|'receipt'
export function IntakeFlow(){
 const initial=new URLSearchParams(location.search).get('business')||''
 const [business,setBusiness]=useState<string>(CURRENT_BUSINESSES.some(b=>b===initial)?initial:'')
 const [hours,setHours]=useState(''),[pains,setPains]=useState<string[]>([]),[stage,setStage]=useState<Stage>('questions')
 const [email,setEmail]=useState(''),[consent,setConsent]=useState(false),[website,setWebsite]=useState(''),[preferences,setPreferences]=useState('')
 const [intent,setIntent]=useState<'plan'|'call'>('plan'),[validation,setValidation]=useState('')
 const [receipt,setReceipt]=useState<{email:string;intent:'plan'|'call'}|null>(null)
 const {submit,busy,error,setError}=useSubmission();const heading=useRef<HTMLHeadingElement>(null);const painGroup=useRef<HTMLFieldSetElement>(null)
 useEffect(()=>{heading.current?.focus()},[stage])
 function move(next:Stage){if(busy)return;setValidation('');setError('');setStage(next)}
 function seeIdeas(e:FormEvent){e.preventDefault();if(!pains.length){setValidation('Choose at least one task to see relevant ideas.');painGroup.current?.focus();return}move('ideas')}
 async function send(e:FormEvent){e.preventDefault();if(!consent)return;const sent={email,intent};const payload={business,hours,pains,email,consent,website,intent,preferences:intent==='call'?preferences:''};if(await submit('/api/leads',payload)){setReceipt(sent);setStage('receipt')}}
 const titles={questions:'What could work better?',ideas:'A few places to start.',contact:'Talk through the next step.',receipt:'Your request is saved.'}
 return <div className="lv-form-page"><p className="lv-eyebrow">{stage==='questions'?'FIND YOUR STARTING POINT':stage==='ideas'?'YOUR STARTING POINTS':stage==='contact'?'OPTIONAL FOLLOW-UP':'REQUEST RECEIVED'}</p><h1 ref={heading} tabIndex={-1}>{titles[stage]}</h1>
 {stage==='questions'&&<><p className="lv-lead">Three questions to find relevant ideas. No email needed.</p><SubmissionForm onSubmit={seeIdeas}><div className="lv-field"><label htmlFor="business">1. What kind of business do you run?</label><select id="business" required value={business} onChange={e=>setBusiness(e.target.value)}><option value="">Choose your business</option>{CURRENT_BUSINESSES.map(b=><option key={b}>{b}</option>)}</select></div><fieldset><legend>2. How much time goes to admin each week?</legend><div className="lv-choice-grid">{PUBLIC_HOURS.map(h=><label key={h} className="lv-native-choice"><input type="radio" name="hours" id={`hours-${h.replaceAll(' ','-')}`} required checked={hours===h} onChange={()=>setHours(h)}/>{h} hours</label>)}</div></fieldset><fieldset ref={painGroup} tabIndex={-1} aria-describedby={validation?'pain-error':undefined}><legend>3. Which tasks do you repeat?</legend><p className="lv-small lv-muted">Choose all that apply.</p><div className="lv-stack">{PUBLIC_PAINS.map(p=><label key={p.id} className="lv-native-choice"><input type="checkbox" checked={pains.includes(p.id)} onChange={()=>{setPains(v=>v.includes(p.id)?v.filter(x=>x!==p.id):[...v,p.id]);setValidation('')}}/>{p.label}</label>)}</div>{validation&&<p id="pain-error" role="alert" className="lv-error">{validation}</p>}</fieldset><button className="lv-button">See my ideas <span aria-hidden="true">↗</span></button><p className="lv-small lv-muted">Your answers stay in this tab until you choose to submit a contact request. Refreshing clears this draft.</p></SubmissionForm></>}
 {stage==='ideas'&&<div className="lv-stack"><p className="lv-lead">Based on the tasks you selected. These are ideas to investigate—not a completed assessment or a savings promise.</p><p className="lv-small lv-muted">{business} · {hours} hours of admin per week</p>{PUBLIC_PAINS.filter(p=>pains.includes(p.id)).map(p=>{const g=GUIDANCE[p.id];return <article className="lv-card lv-guidance" key={p.id}><p className="lv-eyebrow">{g.task}</p><h2>{g.title}.</h2><h3>What could change</h3><p>{g.change}</p><h3>Check before building</h3><p>{g.check}</p><h3>Keep a person involved</h3><p>{g.control}</p></article>})}<aside className="lv-note"><h2>Choose one useful change.</h2><p>Compare how often each task happens, the effort involved and what could go wrong. There is no automatic ranking: the right starting point depends on your work.</p><button className="lv-button" onClick={()=>{setConsent(false);move('contact')}}>Discuss these ideas</button><p className="lv-small lv-muted">Sharing your details is optional.</p></aside><div className="lv-actions"><button className="lv-button secondary" onClick={()=>move('questions')}>Edit answers</button><button className="lv-button secondary" onClick={()=>window.print()}>Print or save ideas</button></div>{receipt?<p className="lv-small" role="status">Your earlier {receipt.intent==='call'?'call':'follow-up'} request for {receipt.email} was saved. <button className="lv-inline-button" onClick={()=>move('receipt')}>View receipt</button></p>:<p className="lv-small lv-muted">Nothing has been submitted.</p>}</div>}
 {stage==='contact'&&<><p>Share your answers only if you want to hear from Levarum.</p><SubmissionForm busy={busy} onSubmit={send}><div className="lv-field"><label htmlFor="email">Email</label><input id="email" type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></div><fieldset><legend>How would you like to follow up?</legend><div className="lv-stack">{([['plan','Email me about these ideas'],['call','Request a 15-minute call']] as const).map(([value,label])=><label className="lv-native-choice" key={value}><input type="radio" name="intent" checked={intent===value} onChange={()=>{setIntent(value);setConsent(false);setError('')}}/>{label}</label>)}</div></fieldset>{intent==='call'&&<div className="lv-field"><label htmlFor="preferences">When usually works for you? Include your timezone. <span className="lv-muted">(Optional)</span></label><textarea id="preferences" maxLength={500} value={preferences} onChange={e=>setPreferences(e.target.value)}/></div>}<label className="lv-consent"><input id="consent" type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/>I agree that Levarum can store my answers and contact me about this {intent==='call'?'call request':'follow-up request'}. <a href="/privacy" target="_blank" rel="noreferrer">Privacy notice (opens a new tab)</a>.</label><label className="lv-honeypot" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label>{error&&<p role="alert" className="lv-error">{error}</p>}<button className="lv-button" disabled={busy}>{busy?'Saving your request…':intent==='call'?'Send my call request':'Send my follow-up request'}</button><p className="lv-small lv-muted">{intent==='call'?'A request does not book an appointment. We arrange calls by email.':'Your starting points are not automatically emailed. You can print or save them from the ideas screen.'}</p><button type="button" className="lv-button secondary" disabled={busy} onClick={()=>move('ideas')}>Back to my ideas</button></SubmissionForm></>}
 {stage==='receipt'&&receipt&&<div className="lv-card lv-stack"><p>Levarum will follow up at <strong>{receipt.email}</strong>.</p>{receipt.intent==='call'?<p>Your call request is saved. We will agree a time by email. This is not a confirmed appointment.</p>:<p>Your follow-up request is saved for review. Your starting points have not been automatically emailed.</p>}<button className="lv-button" onClick={()=>move('ideas')}>Back to my ideas</button><a href="mailto:hello@levarum.com">hello@levarum.com</a></div>}
 </div>
}
