import { SubmissionForm } from './SubmissionForm'
import { useEffect, useRef, useState, type FormEvent } from 'react'
import { CURRENT_BUSINESSES, PUBLIC_HOURS, PUBLIC_PAINS } from '../domain/public'
import { useSubmission } from './useSubmission'
export function IntakeFlow(){
 const initial=new URLSearchParams(location.search).get('business')||''
 const [business,setBusiness]=useState<string>(CURRENT_BUSINESSES.some(b=>b===initial)?initial:'')
 const [hours,setHours]=useState(''),[pains,setPains]=useState<string[]>([]),[step,setStep]=useState(1)
 const [email,setEmail]=useState(''),[consent,setConsent]=useState(false),[website,setWebsite]=useState(''),[preferences,setPreferences]=useState('')
 const [validation,setValidation]=useState('')
 const heading=useRef<HTMLHeadingElement>(null)
 const {submit,busy,error,setError}=useSubmission()
 useEffect(()=>{heading.current?.focus()},[step])
 const selected=PUBLIC_PAINS.filter(p=>pains.includes(p.id))
 function move(next:number){setValidation('');setError('');setStep(next)}
 function next(e:FormEvent){e.preventDefault();if(step===2&&!pains.length){setValidation('Choose at least one job.');return}move(step+1)}
 async function save(e:FormEvent){e.preventDefault();if(!consent)return;const intent=step===6?'call':'plan';if(await submit('/api/leads',{business,hours,pains,email,consent,preferences:intent==='call'?preferences:'',website,intent}))move(intent==='call'?7:5)}
 const titles:Record<number,string>={1:'First, the basics.',2:'Where does the week actually go?',3:'Here is what I will put together.',4:'Your Game Plan is ready.',5:'A few jobs worth exploring.',6:'Let’s find a time.',7:'Call request received.'}
 return <div className="lv-form-page"><p className="lv-eyebrow">{step<=3?`STEP ${step} OF 3`:'YOUR GAME PLAN'}</p><h1 ref={heading} tabIndex={-1}>{titles[step]}</h1>
 {step<=3&&<SubmissionForm onSubmit={next}>
 {step===1&&<><p>Two quick facts about your week. No account, no card.</p><label htmlFor="business">What kind of business is this?</label><select id="business" required value={business} onChange={e=>setBusiness(e.target.value)}><option value="">Choose your business</option>{CURRENT_BUSINESSES.map(b=><option key={b}>{b}</option>)}</select><fieldset><legend>Hours a week on back-office work</legend><div className="lv-choice-grid">{PUBLIC_HOURS.map(h=><label key={h} className="lv-native-choice"><input type="radio" name="hours" value={h} checked={hours===h} required onChange={()=>setHours(h)}/>{h} hours</label>)}</div></fieldset></>}
 {step===2&&<fieldset aria-describedby={validation?'pain-error':undefined}><legend>Pick the ones that sound like you.</legend><div className="lv-stack">{PUBLIC_PAINS.map(p=><label key={p.id} className="lv-native-choice"><input type="checkbox" checked={pains.includes(p.id)} onChange={()=>{setPains(v=>v.includes(p.id)?v.filter(id=>id!==p.id):[...v,p.id]);setValidation('')}}/>{p.label}</label>)}</div>{validation&&<p id="pain-error" role="alert" className="lv-error">{validation}</p>}</fieldset>}
 {step===3&&<><p>A practical plan based on the challenges you selected.</p><ol className="lv-promise"><li>The jobs worth reviewing first.</li><li>Questions to check before changing your workflow.</li><li>An optional fifteen-minute conversation.</li></ol><p className="lv-muted">Time saved depends on the actual work. This plan does not promise a number of hours or a financial return.</p></>}
 <div className="lv-actions">{step>1&&<button type="button" className="lv-button secondary" onClick={()=>move(step-1)}>Back</button>}<button className="lv-button">{step===3?'Build my Game Plan':'Next'}</button></div></SubmissionForm>}
 {step===4&&<SubmissionForm busy={busy} onSubmit={save}><p>{selected.length} {selected.length===1?'job':'jobs'} to explore for your {business.toLowerCase()} business.</p><ul>{selected.map(p=><li key={p.id}>{p.label}</li>)}</ul><p>Save your intake to see the plan on screen. Levarum can contact you about your answers. The plan is not automatically emailed.</p><label htmlFor="email">Email</label><input id="email" type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/><label className="lv-consent"><input id="consent" type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/>I agree that Levarum can store my answers and contact me about this request. <a href="/privacy" target="_blank" rel="noreferrer">Privacy notice</a>.</label><label className="lv-honeypot" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label>{error&&<p role="alert" className="lv-error">{error}</p>}<button className="lv-button" disabled={busy}>{busy?'Saving your request…':'Save and view my plan'}</button><button type="button" className="lv-button secondary" disabled={busy} onClick={()=>move(3)}>← Back a step</button></SubmissionForm>}
 {step===5&&<div className="lv-stack"><p>Your intake is saved. Use this as a starting point for reviewing the work, not a savings guarantee.</p>{selected.map((p,i)=><article className="lv-card" key={p.id}><p className="lv-eyebrow">OPPORTUNITY {i+1}</p><h2>{p.outcome}</h2><p>Record how often this happens, how long it takes, and where someone needs to check the result.</p></article>)}<aside className="lv-card tinted"><h2>Choose one small starting point.</h2><p>Start by reviewing {selected[0]?.label.toLowerCase()}. Compare frequency, effort and risk across these jobs. On the call, we can decide which one is worth changing first.</p></aside><div className="lv-actions"><button className="lv-button" onClick={()=>move(6)}>Request a 15-minute call</button><button className="lv-button secondary" onClick={()=>window.print()}>Print or save plan</button></div></div>}
 {step===6&&<SubmissionForm busy={busy} onSubmit={save}><p>I will reply to <strong>{email}</strong> to agree a time. Nothing is booked yet.</p><label htmlFor="preferences">When usually works for you? Include your timezone. <span className="lv-muted">(Optional)</span></label><textarea id="preferences" maxLength={500} value={preferences} onChange={e=>setPreferences(e.target.value)}/>{error&&<p role="alert" className="lv-error">{error}</p>}<button className="lv-button" disabled={busy}>{busy?'Saving your request…':'Send my call request'}</button><button type="button" className="lv-button secondary" disabled={busy} onClick={()=>move(5)}>Back to my plan</button></SubmissionForm>}
 {step===7&&<div className="lv-card lv-stack"><p>Your request is saved. I will contact <strong>{email}</strong> to arrange a time. This is not a confirmed appointment.</p><a href="mailto:hello@levarum.com">hello@levarum.com</a><button className="lv-button secondary" onClick={()=>move(5)}>View my plan</button><a href="/start">Start again</a></div>}
 </div>
}
