import type { PainId, Submission, SubmissionStatus } from '../../domain/types'
import { PAINS } from '../../domain/pains'
import { CATALOG, optionFor } from '../../domain/catalog'
import { stackTotals, timeAgo } from '../../domain/estimate'
import { ThemeToggle } from '../../components/ThemeToggle'

/**
 * One submission, scoped.
 *
 * Reads the same intake the prospect filled in, shows Claude's draft approach,
 * and maps each named pain to a real, buildable workflow the operator can swap.
 * Effort and tooling cost roll up from whatever is currently chosen, which is
 * what the build estimate is derived from.
 */

interface DetailProps {
  submission: Submission
  onBack: () => void
  onSignOut: () => void
  onRegenerate: () => void
  onStatus: (status: SubmissionStatus) => void
  onSwap: (painId: PainId, optionId: string) => void
}

const STATUS_ACTIONS: { key: SubmissionStatus; label: string }[] = [
  { key: 'new', label: 'Mark new' },
  { key: 'contacted', label: 'Contacted' },
  { key: 'archived', label: 'Archive' },
]

function draftBadge(sub: Submission) {
  if (sub.draft.status === 'pending') return { label: 'Generating', className: 'op-badge--wait' }
  if (sub.draft.source === 'fallback') {
    return { label: 'Offline draft', className: 'op-badge--offline' }
  }
  return { label: 'Generated by Claude', className: 'op-badge--ai' }
}

export function Detail({
  submission,
  onBack,
  onSignOut,
  onRegenerate,
  onStatus,
  onSwap,
}: DetailProps) {
  const { draft } = submission
  const pains = PAINS.filter((p) => submission.pains.includes(p.id))
  const totals = stackTotals(draft.stack)
  const badge = draftBadge(submission)
  const pending = draft.status === 'pending'

  return (
    <>
      <div className="op-bar">
        <div className="op-bar-row">
          <button type="button" className="op-link" onClick={onBack}>
            ‹ Inbox
          </button>
          <span className="op-bar-actions">
            <ThemeToggle />
            <button type="button" className="op-link" onClick={onSignOut}>
              Sign out
            </button>
          </span>
        </div>
        <div className="op-detail-head">{submission.business}</div>
        <div className="op-detail-meta">
          {submission.email} · {timeAgo(submission.createdAt)}
        </div>
      </div>

      <div className="op-body">
        {/* From the intake */}
        <section className="op-card">
          <div className="op-label">From the intake</div>
          <div className="op-intake-grid">
            <div>
              <div className="op-intake-label">Back-office hours</div>
              <div className="op-intake-value">{submission.hours} / week</div>
            </div>
            <div>
              <div className="op-intake-label">Est. hours back</div>
              <div className="op-intake-value">
                {draft.hoursLo} to {draft.hoursHi} hrs / week
              </div>
            </div>
            <div>
              <div className="op-intake-label">Their hourly rate</div>
              <div className="op-intake-value">${submission.rate} / hr</div>
            </div>
          </div>
          <div className="op-chips" style={{ marginTop: 14 }}>
            {pains.map((p) => (
              <span className="op-chip" key={p.id}>
                {p.short}
              </span>
            ))}
          </div>
        </section>

        {/* Draft approach */}
        <section className="op-card op-draft-card">
          <div className="op-draft-head">
            <span className="op-draft-title">
              <span className="op-spark" aria-hidden="true" />
              Draft approach
            </span>
            <span className={`op-badge ${badge.className}`}>{badge.label}</span>
          </div>

          {pending ? (
            <div className="op-drafting" role="status">
              <span className="op-spinner" aria-hidden="true" />
              Claude is drafting the approach…
            </div>
          ) : (
            <>
              <p className="op-summary">{draft.summary}</p>
              <ol className="op-phases">
                {draft.phases.map((phase) => (
                  <li key={phase.n}>
                    <span className="op-phase-n" aria-hidden="true">
                      {phase.n}
                    </span>
                    <span className="op-phase-text">
                      <b>{phase.title}</b> {phase.detail}
                    </span>
                  </li>
                ))}
              </ol>
              <button type="button" className="op-regen" onClick={onRegenerate}>
                ↻ Regenerate with Claude
              </button>
            </>
          )}
        </section>

        {/* Recommended workflow stack: real tools, operator only */}
        <section className="op-card">
          <div className="op-stack-head">
            <span className="op-label" style={{ marginBottom: 0 }}>
              Recommended workflow stack
            </span>
            <span className="op-stack-note">real tools · operator only</span>
          </div>

          <div className="op-stack">
            {draft.stack.map((item) => {
              const entry = CATALOG[item.painId]
              const option = optionFor(item)
              return (
                <article className="op-workflow" key={item.painId}>
                  <div className="op-workflow-pain">{item.painShort}</div>
                  <div className="op-workflow-name">{option.name}</div>
                  <div className="op-workflow-why">{item.why}</div>

                  <div className="op-trigger">
                    <span className="op-trigger-tag">Trigger</span>
                    <span className="op-trigger-text">{option.trigger}</span>
                  </div>

                  <ol className="op-steps">
                    {option.steps.map((step) => (
                      <li key={step.tool + step.action}>
                        <span className="op-step-dot" aria-hidden="true" />
                        <span>
                          <b>{step.tool}</b> {step.action}
                        </span>
                      </li>
                    ))}
                  </ol>

                  <div className="op-tools">
                    {option.tools.map((tool) => (
                      <span className="op-tool" key={tool}>
                        {tool}
                      </span>
                    ))}
                  </div>

                  <div className="op-workflow-meta">
                    <span>
                      Build <b>{option.effort}</b>
                    </span>
                    <span>
                      Tools <b>{option.cost}</b>
                    </span>
                  </div>

                  <div className="op-swap">
                    <div className="op-swap-label">Swap the approach</div>
                    <div className="op-swap-options">
                      {entry.options.map((alt) => (
                        <button
                          key={alt.id}
                          type="button"
                          className="op-swap-option"
                          aria-pressed={alt.id === item.optionId}
                          onClick={() => onSwap(item.painId, alt.id)}
                        >
                          {alt.name}
                        </button>
                      ))}
                    </div>
                  </div>
                </article>
              )
            })}
          </div>

          <div className="op-total">
            <span>Stack total</span>
            <b>
              {totals.effortLabel} · {totals.toolingLabel} tools
            </b>
          </div>
        </section>

        {/* Working notes */}
        <div className="op-working">
          <section className="op-card">
            <div className="op-label">What to measure</div>
            <ul className="op-list">
              {draft.measure.map((line) => (
                <li key={line}>
                  <span className="op-bullet" aria-hidden="true" />
                  <span>{line}</span>
                </li>
              ))}
            </ul>
          </section>

          <section className="op-card">
            <div className="op-label">Discovery questions</div>
            <ul className="op-list">
              {draft.discovery.map((line) => (
                <li key={line}>
                  <span>{line}</span>
                </li>
              ))}
            </ul>
          </section>

          <section className="op-card">
            <div className="op-label">Watch-outs</div>
            <ul className="op-list">
              {draft.watchouts.map((line) => (
                <li key={line}>
                  <span className="op-bang" aria-hidden="true">
                    !
                  </span>
                  <span>{line}</span>
                </li>
              ))}
            </ul>
          </section>
        </div>

        {/* Rough build estimate */}
        <section className="op-card op-card--focal op-estimate-card">
          <div>
            <div className="op-label">Rough build estimate</div>
            <div className="op-estimate">
              <div>
                <div className="op-estimate-label">Effort</div>
                <div className="op-estimate-value">{totals.effortLabel}</div>
              </div>
              <div>
                <div className="op-estimate-label">Range</div>
                <div className="op-estimate-value">{totals.buildRange}</div>
              </div>
            </div>
          </div>
          <div className="op-never">Your sizing only. Never shown to the prospect.</div>
        </section>

        <div className="op-label">Status</div>
        <div className="op-status">
          {STATUS_ACTIONS.map((action) => (
            <button
              key={action.key}
              type="button"
              aria-pressed={submission.status === action.key}
              onClick={() => onStatus(action.key)}
            >
              {action.label}
            </button>
          ))}
        </div>

        {submission.bookedSlot ? (
          <div className="op-foot">Call booked for {submission.bookedSlot}.</div>
        ) : null}
      </div>
    </>
  )
}
