import { GUIDANCE } from '../domain/guidance'

export function StartLink({secondary=false}:{secondary?:boolean}){return <a className={`lv-button${secondary?' secondary':''}`} href="/start">Find my starting point <span aria-hidden="true">↗</span></a>}
function Closing(){return <section className="lv-closing"><div className="lv-container"><p className="lv-eyebrow">ONE USEFUL CHANGE AT A TIME</p><h2>What would you like off your plate?</h2><p>Choose the tasks that take up your week. See practical starting points before sharing contact details.</p><StartLink/></div></section>}
export function Home(){return <>
 <section className="lv-container lv-hero"><div><p className="lv-eyebrow">PRACTICAL AUTOMATION FOR OWNER-RUN BUSINESSES</p><h1>Less admin.<br/><span>More room to run your business.</span></h1><p className="lv-lead">Levarum helps you simplify repetitive work—from invoice follow-up to keeping tools in sync. Start by finding a task worth improving.</p><div className="lv-actions"><StartLink/><a className="lv-text-link" href="/what-we-automate">See what we automate →</a></div><p className="lv-small lv-muted">No account or email needed to explore ideas.</p></div>
 <aside className="lv-workflow" aria-label="Illustrative invoice follow-up workflow"><p className="lv-eyebrow">A SMALL CHANGE, CLEARLY DEFINED</p><h2>Follow up on invoices without the spreadsheet chase.</h2><ol>{['Invoice becomes overdue','Check the exceptions you agreed','Send an approved reminder','Flag anything that needs you'].map((x,i)=><li key={x}><span aria-hidden="true">0{i+1}</span>{x}</li>)}</ol><p className="lv-small lv-muted">Illustrative workflow. Tools, rules and approvals are agreed before building.</p></aside></section>
 <section className="lv-section lv-soft"><div className="lv-container"><div className="lv-section-intro"><p className="lv-eyebrow">RECOGNIZE ANY OF THESE?</p><h2>Start with work you repeat.</h2><p>A useful automation begins with a clear task—not a new collection of tools.</p></div><div className="lv-job-grid">{Object.entries(GUIDANCE).map(([id,g],i)=><a className="lv-job" key={id} href={`/what-we-automate#${id}`}><span className="lv-job-number">0{i+1}</span><h3>{g.task}</h3><p>{g.change}</p><span className="lv-text-link">Explore this task <span aria-hidden="true">↗</span></span></a>)}</div></div></section>
 <section className="lv-section lv-container"><div className="lv-section-intro"><p className="lv-eyebrow">HOW WE GET THERE</p><h2>Understand it. Try it. Keep control.</h2></div><div className="lv-three">{[['01','Find a starting point','Tell us which tasks repeat. See ideas and the questions to check before changing anything.'],['02','Talk it through','If useful, request follow-up or a short call. We arrange calls by email.'],['03','Agree the work','Scope, price, access and handover are agreed before a build begins.']].map(([n,t,b])=><div key={n}><p className="lv-eyebrow">{n}</p><h3>{t}</h3><p className="lv-muted">{b}</p></div>)}</div><a className="lv-text-link" href="/how-it-works">Read the process →</a></section><Closing/>
 </>}
export function How(){return <><section className="lv-container lv-page-intro"><p className="lv-eyebrow">HOW IT WORKS</p><h1>Start with one<br/>useful improvement.</h1><p className="lv-lead">You do not need to know which software or automation to buy. Begin with the work that keeps repeating.</p></section><section className="lv-container lv-process">{[['Describe the work','Select your business type, weekly admin time and recurring tasks. Your answers stay in this tab until you choose to contact us.'],['Review your starting points','See practical ideas and what to check before making changes. These are starting points, not a completed assessment or a promise of time saved.'],['Ask for help, if useful','Send your details for email follow-up or request a 15-minute call. A request is not a booking; we agree a time by email.'],['Agree the work before building','Confirm scope, price, timeline, access, handover and support. Any additional tools or subscriptions are discussed before you commit.']].map(([t,b],i)=><article key={t}><span className="lv-job-number">0{i+1}</span><div><h2>{t}</h2><p>{b}</p></div></article>)}</section><Closing/></>}
export function Automations(){return <><section className="lv-container lv-page-intro"><p className="lv-eyebrow">WHAT WE AUTOMATE</p><h1>Five places to<br/>reduce repeat work.</h1><p className="lv-lead">These are examples we can explore. What fits depends on your tools, workload and the decisions that need a person.</p></section><section className="lv-container lv-examples">{Object.entries(GUIDANCE).map(([id,g],i)=><article id={id} className="lv-example" key={id}><div><p className="lv-eyebrow">0{i+1} / {g.task.toUpperCase()}</p><h2>{g.title}.</h2></div><div><h3>What could change</h3><p>{g.change}</p><h3>Check before building</h3><p>{g.check}</p><h3>Keep a person involved</h3><p>{g.control}</p></div></article>)}</section><Closing/></>}
const FAQS=[
 ['What does it cost?','The on-screen starting points are free to explore. Any implementation is scoped and priced separately before work begins. Additional tools or subscriptions are discussed as part of that scope.'],
 ['What happens when I request contact?','Your request is saved privately for review. Levarum follows up by email. If you ask for a call, we agree a time together; submitting does not book an appointment.'],
 ['Will this work with my existing tools?','We review what you already use before recommending a change. Compatibility, access requirements and any additional subscriptions must be checked before a build.'],
 ['Do I need technical knowledge?','No. Start with the work you repeat. The first conversation is about your process, the people involved and what would make it easier.'],
 ['Will I stay in control?','Approvals, exceptions and access are agreed before implementation. Some decisions should stay with a person. Account ownership and handover are included in the scope.'],
 ['What about support?','Support, monitoring and responsibility for changes are agreed before work starts. The right arrangement depends on what is built.'],
 ['What happens to my information?','You can explore ideas without submitting your answers. If you request contact, we store the information you submit privately to handle that request. The privacy notice explains how to contact us about your data.'],
 ['Will you email my starting points automatically?','No. You can print or save them from the results screen. If you request follow-up, Levarum reviews your request and responds by email.'],
]
export function Questions(){return <><section className="lv-container lv-page-intro"><p className="lv-eyebrow">QUESTIONS</p><h1>A little clarity<br/>before you start.</h1><p className="lv-lead">Cost, tools, privacy and what happens next.</p></section><section className="lv-container lv-faqs">{FAQS.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}{q==='What happens to my information?'&&<> <a href="/privacy">Read the privacy notice.</a></>}</p></details>)}<div className="lv-note"><h2>Something else on your mind?</h2><p>Email <a href="mailto:hello@levarum.com">hello@levarum.com</a>. You do not need to complete the questionnaire to ask a question.</p></div></section><Closing/></>}
