import { FieldValidation, SubmissionError, SubmissionForm } from '../prospect/SubmissionForm'
import { useEffect, useRef, useState, type FormEvent } from 'react'
import { CONTRIBUTIONS } from '../domain/public'
import { useSubmission } from '../prospect/useSubmission'
export function Partners(){
 const [name,setName]=useState(''),[craft,setCraft]=useState(''),[contribution,setContribution]=useState(''),[email,setEmail]=useState(''),[consent,setConsent]=useState(false),[website,setWebsite]=useState(''),[saved,setSaved]=useState(false)
 const {submit,busy,error}=useSubmission();const heading=useRef<HTMLHeadingElement>(null)
 useEffect(()=>{if(saved)heading.current?.focus()},[saved])
 async function send(e:FormEvent){e.preventDefault();if(await submit('/api/partners',{name,craft,contribution,email,consent,website}))setSaved(true)}
 return <div className="lv-form-page"><p className="lv-eyebrow">IMPLEMENTATION PARTNERS</p><h1 ref={heading} tabIndex={-1}>{saved?'Your partner interest is saved.':'Build practical improvements with Levarum.'}</h1>{saved?<div className="lv-card"><p>We will review your details and contact you if there is a fit. This is an expression of interest, not an offer of work.</p><a href="/">Back to the site</a><p><a href="/partners">Add another</a></p></div>:<><p>If you build automations or support the operations of service businesses, tell us where you would fit. Scope, availability and terms are agreed separately.</p><SubmissionForm busy={busy} onSubmit={send}><label htmlFor="partner-name">Your name</label><input id="partner-name" autoComplete="name" required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/><FieldValidation name="partner-name"/><label htmlFor="craft">What do you do?</label><textarea id="craft" required maxLength={1000} value={craft} onChange={e=>setCraft(e.target.value)}/><FieldValidation name="craft"/><fieldset><legend>How would you like to contribute?</legend><div className="lv-choice-grid">{CONTRIBUTIONS.map(c=><label className="lv-native-choice" key={c}><input type="radio" name="contribution" required checked={contribution===c} onChange={()=>setContribution(c)}/>{c}</label>)}</div></fieldset><FieldValidation name="contribution"/><label htmlFor="partner-email">Email</label><input id="partner-email" type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/><FieldValidation name="partner-email"/><label className="lv-consent"><input id="consent" type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/>I agree that Levarum can store these details and contact me about my interest. <a href="/privacy" target="_blank" rel="noreferrer">Privacy notice</a>.</label><FieldValidation name="consent"/><label className="lv-honeypot" aria-hidden="true">Website<input value={website} onChange={e=>setWebsite(e.target.value)} tabIndex={-1} autoComplete="off"/></label><SubmissionError message={error}/><button className="lv-button" disabled={busy}>{busy?'Saving…':'Send partner interest'}</button></SubmissionForm></>}</div>
}
